<template>
  <atom-animated-wrapper class="animate__fadeIn">
    <div class="loadingio-spinner-double-ring-j4uqqjzx04">
      <div class="ldio-udrx6d3rqep">
        <div></div>
        <div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
    </div>
  </atom-animated-wrapper>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AtomAnimatedWrapper from "@/components/atoms/AtomAnimatedWrapper.vue";

export default defineComponent({
  name: "MoleculeLoader",
  components: {
    AtomAnimatedWrapper
  }
});
</script>

<style type="text/css" lang="scss">
@keyframes ldio-udrx6d3rqep {
  0% {
    transform: translate(-50%, -50%) rotate(0);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}

.ldio-udrx6d3rqep div {
  box-sizing: border-box !important;
}
.ldio-udrx6d3rqep > div {
  position: absolute;
  top: 50%;
  left: 50%;

  width: 144px;
  height: 144px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: $main-color transparent $main-color transparent;

  animation: ldio-udrx6d3rqep 1s linear infinite;
}

.ldio-udrx6d3rqep > div:nth-child(2),
.ldio-udrx6d3rqep > div:nth-child(4) {
  top: 50%;
  left: 50%;
  width: 108px;
  height: 108px;
  animation: ldio-udrx6d3rqep 1s linear infinite reverse;
}
.ldio-udrx6d3rqep > div:nth-child(2) {
  border-color: transparent #d1ebfd transparent #d1ebfd;
}
.ldio-udrx6d3rqep > div:nth-child(3) {
  border-color: transparent;
}
.ldio-udrx6d3rqep > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-udrx6d3rqep > div:nth-child(3) div:before,
.ldio-udrx6d3rqep > div:nth-child(3) div:after {
  content: "";

  position: absolute;
  top: -16px;
  left: 48px;

  display: block;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 $main-color;

  background: $main-color;
}
.ldio-udrx6d3rqep > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 $main-color;
}

.ldio-udrx6d3rqep > div:nth-child(4) {
  border-color: transparent;
}
.ldio-udrx6d3rqep > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-udrx6d3rqep > div:nth-child(4) div:before,
.ldio-udrx6d3rqep > div:nth-child(4) div:after {
  content: "";

  position: absolute;
  top: -16px;
  left: 30px;

  display: block;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #d1ebfd;

  background: #d1ebfd;
}
.ldio-udrx6d3rqep > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #d1ebfd;
}
.loadingio-spinner-double-ring-j4uqqjzx04 {
  position: relative;
  display: inline-block;
  width: 100%;
  height: 200px;
  overflow: hidden;
}
.ldio-udrx6d3rqep {
  position: relative;

  width: 100%;
  height: 100%;

  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-udrx6d3rqep div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
